Older Work/Boox - sophmore year website sample/BooX/BooX/Controllers/SearchRController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooX.Models;
using System.Dynamic;

namespace BooX.Controllers
{
    public class SearchRController : Controller
    {
        private Model1 db = new Model1();
        
        // GET: SearchR
      

        public ActionResult Index(string searchString, string searchBy)
        {
           
            var bks = from m in db.Books select m;
            List<int> bookIDs = new List<int>();
            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchBy))
            {
                if (searchBy == "0")
                {
                    bks = bks.Where(s => s.Title.Contains(searchString));
                }
                else if (searchBy == "1")
                {
                    bks = bks.Where(s => s.Author_Name.Contains(searchString));
                }
                else if (searchBy == "2")
                {
                    bks = bks.Where(s => s.Publisher_Name.Contains(searchString));
                }
                foreach (var b in bks)
                {
                    bookIDs.Add(b.Id);
                }
                //return View(bks);
                return DisplayListing(bookIDs);
            }
            return null;
        }

        
        public ActionResult DisplayListing(List<int> b_ID)
        {
            var lst = from l in db.Listings
                      select l;
            var a = lst.Where(s => b_ID.Contains(s.Book_ID));
            List <Listing> b = new List <Listing>();
            foreach (var i in a)
            {
                if (i.Status_ID == 1)
                {
                    b.Add(i);
                }
            }
            return View(b);
        }


        // GET: SearchR/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: SearchR/Create
        public ActionResult Create()
        {
            ViewBag.Author_ID = new SelectList(db.Books, "Publisher", "Publisher");
            ViewBag.Publisher_ID = new SelectList(db.Books, "Author", "Author");
            return View();
        }

        // POST: SearchR/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ISBN,Title,Author_ID,Publisher_ID,Year,Edition,Image")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Author_ID = new SelectList(db.Books, "Id", "Author_Name", book.Author_Name);
            ViewBag.Publisher_ID = new SelectList(db.Books, "Id", "Publisher_Name", book.Publisher_Name);
            return View(book);
        }

        // GET: SearchR/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.Author_ID = new SelectList(db.Books, "Id", "Author_Name", book.Author_Name);
            ViewBag.Publisher_ID = new SelectList(db.Books, "Id", "Publisher_Name", book.Publisher_Name);
            return View(book);
        }

        // POST: SearchR/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ISBN,Title,Author_ID,Publisher_ID,Year,Edition,Image")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Author_ID = new SelectList(db.Books, "Id", "Author_Name", book.Author_Name);
            ViewBag.Publisher_ID = new SelectList(db.Books, "Id", "Publisher_Name", book.Publisher_Name);
            return View(book);
        }

        // GET: SearchR/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: SearchR/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/SearchR/Create.cshtml
@model BooX.Models.Book

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author_ID, "Author_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Author_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Author_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publisher_ID, "Publisher_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Publisher_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Publisher_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/SearchR/Delete.cshtml
@model BooX.Models.Book

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_navbar.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.Author_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Author_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher.Publisher_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher.Publisher_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/SearchR/Details.cshtml
@model BooX.Models.Book

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_navbar.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/SearchR/Edit.cshtml
@model BooX.Models.Book

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_navbar.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author_ID, "Author_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Author_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Author_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publisher_ID, "Publisher_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Publisher_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Publisher_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/SearchR/Index.cshtml
@model IEnumerable<BooX.Models.Listing> 
@{
    ViewBag.Title = "Search Results";
    Layout = "~/Views/Shared/_navbar.cshtml";
}
<style>
    .homepage {
        background-color: transparent;
        color: black;
        text-align: left;
        font-size: 12pt;
        width: auto;
    }
    th{
        text-align:center;
    }

    input {
        border: 2px solid #009635;
        border-radius: 15px;
    }
    p{
        font-size: 20px;
    }
    table {
        background-color: white;
        width: 100%;
        font-size: 20px;
        margin-top: 3%;
        border: 10px solid #009635;
        color: black;
        padding: 10px;
    }
    thead{border :2px solid black}
    tr{margin-top:10px;}
    #sButton{
        background-color: #009635;
        font-weight: bold;
        color: white;
        font-size:25px;
    }
</style>
<div class="homepage">
    <img src='@Url.Content("~/Content/Images/icon_search.png")' style="width:150px; float:left;" />
    <p style="font-size: 59px">Search</p>   
        @using (Html.BeginForm("Index", "SearchR"))
        {
            <p>
                <input type="text" name="searchString" size="40" required="required" />
                Search By: <select name="searchBy">
                    <option value="0">Title</option>
                    <option value="1">Author</option>
                    <option value="2">Publisher</option>
                </select>
                <input type="submit" id="sButton" value="Search" />
            </p>
        }
        <table cellpadding="3">
            <thead><tr>
                <th>Image</th>
                <th>Title</th>
                <th>ISBN</th>
                <th>Author</th>
                <th>Publisher</th>
                <th>Edition</th>
                <th>Year</th>
                <th>Price</th>
                <th>Condition</th>
                <th>Date Listed</th>
                <th>Status</th>
                <th>Message User</th>
                <th>View Profile</th>
            </tr></thead>
            @foreach (var book in Model)
            {
            <tr>
                @{
                var imgName = book.Book_ID + ".jpg";
                }
                <td><img src="~/Content/BookImages/@imgName" width="75" height="100" /></td>
                <td>@book.Book.Title</td>
                <td>@book.Book.ISBN</td>
                <td>@book.Book.Author_Name</td>
                <td>@book.Book.Publisher_Name</td>
                <td>@book.Book.Edition</td>
                <td>@book.Book.Year</td>
                <td>@book.Price</td>
                <td>@book.Condition.Type</td>
                <td>@book.Date_Listed.ToString()</td>
                <td>@book.Status.Value</td>
                <td>@Html.ActionLink("Buy this book!", "CreateMessage", "Master", new { ID = @book.Id }, null)</td>
                <td>@Html.ActionLink(@book.User.Full_name, "otherProfile", "Master", new { userID = @book.User.ID }, null)</td>
            </tr>
            }            
        </table>
</div>