Older Work/Boox - sophmore year website sample/BooX/BooX/Models/Listing.cs
using System.ComponentModel.DataAnnotations;

namespace BooX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Listing")]
    public partial class Listing
    {
        public Listing()
        {
            Sales = new HashSet<Sale>();
           
        }

        public int Id { get; set; }

        public int Book_ID { get; set; }

        
        public int User_ID { get; set; }

        [Required]
        public int Condition_Id { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:c}")]
        public decimal Price { get; set; }

        //[Column(TypeName = "datetime")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime Date_Listed { get; set; }

        [Required]
        public int Status_ID { get; set; }

        [Required]
        public int Course_ID { get; set; }

        public virtual Book Book { get; set; }

        public virtual Condition Condition { get; set; }

        public virtual Status Status { get; set; }

        public virtual Course Course { get; set; }

        public virtual User User { get; set; }

        public virtual ICollection<Sale> Sales { get; set; }

        private Model1 db = new Model1();

 

    }
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooX.Models;


namespace BooX.Controllers
{
    public class ListingsController : Controller
    {
        private Model1 db = new Model1();

        // GET: Listings
        public ActionResult Index()
        {
            var listings = db.Listings.Include(l => l.Book).Include(l => l.Condition).Include(l => l.Status).Include(l => l.User);
            return View(listings.ToList());
        }

        public IQueryable<Listing> list(User user)
        {
             var searchString = 2;
            var Listing = from m in db.Listings select m;

            Listing = Listing.Where(s => s.User_ID.Equals(searchString));
            return Listing;
        }

        // GET: Listings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            return View(listing);
        }

        // GET: Listings/Create
        public ActionResult Create()
        {
            ViewBag.Book_ID = new SelectList(db.Books, "Id", "ISBN");
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type");
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value");
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Email");
            return View();
        }

        // POST: Listings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Book_ID,User_ID,Condition_Id,Price,Date_Listed,Status_ID")] Listing listing)
        {
            if (ModelState.IsValid)
            {
                db.Listings.Add(listing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Book_ID = new SelectList(db.Books, "Id", "ISBN", listing.Book_ID);
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type", listing.Condition_Id);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value", listing.Status_ID);
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Email", listing.User_ID);
            return View(listing);
        }

        // GET: Listings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            ViewBag.Book_ID = new SelectList(db.Books, "Id", "ISBN", listing.Book_ID);
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type", listing.Condition_Id);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value", listing.Status_ID);
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Email", listing.User_ID);
            return View(listing);
        }

        // POST: Listings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Book_ID,User_ID,Condition_Id,Price,Date_Listed,Status_ID")] Listing listing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(listing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Book_ID = new SelectList(db.Books, "Id", "ISBN", listing.Book_ID);
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type", listing.Condition_Id);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value", listing.Status_ID);
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Email", listing.User_ID);
            return View(listing);
        }

        // GET: Listings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            return View(listing);
        }

        // POST: Listings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Listing listing = db.Listings.Find(id);
            db.Listings.Remove(listing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooX.Models;
using System.IO;
using System.Data.SqlClient;
using System.Text;
using System.Windows;

namespace BooX.Controllers
{
    public class MasterController : Controller
    {
        private Model1 db = new Model1();
       
        static User loggedInUser = new User();

       public ActionResult Reset()
       {
           return View();
       }

       public ActionResult LogOut()
       {
          loggedInUser.ID = 0;
          loggedInUser.Email = null;
          loggedInUser.Password = null;
          loggedInUser.Full_name = null;

          return RedirectToAction("Index", "Home");
       }
       public ActionResult MessageIndex()
       {
         
           var messages = db.Messages.Where(s => s.To_UserID.Equals(loggedInUser.ID));
           List<Message> Message = new List<Message>();

           foreach( var i in messages)
           {
               Message.Add(i);
           }

           return View(Message);
       }

        public ActionResult displayListing (Listing listing)
       {
           return View(listing);
       }

       [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult CreateMessage([Bind(Include = "Id,From_UserID, To_UserID,Listing_ID,Content,Subject,Date")] Message message, int ID)
       {
           if (ModelState.IsValid)
           {
               var Listings = from m in db.Listings select m;
              var lid = Listings.Where(s => s.Id.Equals(ID)).First();
               message.To_UserID = lid.User_ID;
               message.Listing_ID = ID;
               message.From_UserID = loggedInUser.ID;
               db.Messages.Add(message);
               db.SaveChanges();
               return RedirectToAction("MessageIndex");
           }

           return View(message);
       }


       [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult Rating([Bind(Include = "Id, User_ID, rating")] Rating rating)
       {
           rating.User_ID = loggedInUser.ID;
           db.Ratings.Add(rating);
           db.SaveChanges();
           return View();
       }

      


       [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult replyMessage([Bind(Include = "Id,From_UserID,To_UserID,Listing_ID,Content,Subject,Date")] Message message, Message oldMessage)
       {
           if (ModelState.IsValid)
           {
               message.Listing_ID = oldMessage.Listing_ID;
               message.From_UserID = loggedInUser.ID;
               message.To_UserID = oldMessage.From_UserID;
               db.Messages.Add(message);
               db.SaveChanges();
               return RedirectToAction("MessageIndex");
           }

           return View(message);
       }

       public ActionResult replyMessage(Message message)
       {
           return View(message);
       }
       public ActionResult CreateMessage(Message message)
       {
           return View(message);
       }


        public ActionResult bookIndex(User user)
        {
            var searchString = user.ID;
            var Listings = from m in db.Listings select m;

            Listings = Listings.Where(s => s.User_ID.Equals(searchString));

            var allBooks = from m in db.Books select m;

            List<Book> Books = new List<Book>();

            foreach (var i in Listings)
            {   
                var id = i.Book_ID;
                var toAddBook = allBooks.Where(s => s.Id.Equals(id)).First();

                Books.Add(toAddBook);

            }

            return View(Books.ToList());
        }


      
        // GET: Books/Details/5
        public ActionResult BookDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult CreateB()
        {
                
            return View();
        }

        [HttpPost]
        public ActionResult IndexCreateBU(HttpPostedFileBase file, Listing l, Book bk)
        {
            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var f = l.Book_ID + ".jpg";
                var path = Path.Combine(Server.MapPath("~/Content/BookImages"), f);
                file.SaveAs(path);
            }
            return RedirectToAction("Listing", l);
        }

        public ActionResult Listing()
        {
            ViewBag.Course_ID = new SelectList(db.Courses, "Id", "Course_Name");
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type");
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value");
       
            return View();
        }

        public ActionResult ListingIndex (User user)
        {
            var searchString = user.ID;
            var Listings = from m in db.Listings select m;

            Listings = Listings.Where(s => s.User_ID.Equals(searchString));
            return View(Listings.ToList());
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Listing([Bind(Include = "Id,Book_ID,User_ID,Condition_Id,Price,Date_Listed,Status_ID, Course_ID")] Listing listing)
        {
            if (ModelState.IsValid)
            {
                listing.User_ID = loggedInUser.ID;
                if (listing.User_ID == 0) return View();
                db.Listings.Add(listing);
                db.SaveChanges();
                
                return RedirectToAction("Profile");
            }
            ViewBag.Course_ID = new SelectList(db.Courses, "Id", "Course_Name", listing.Course_ID);
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type", listing.Condition_Id);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value", listing.Status_ID);
        
            return View(listing);
           

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditListing([Bind(Include = "Id,Book_ID,User_ID,Condition_Id,Price,Date_Listed,Status_ID, Course_ID")] Listing listing)
        {
            if (ModelState.IsValid)
            {
                listing.User_ID = loggedInUser.ID;
                db.Entry(listing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListingIndex", loggedInUser);
            }

            ViewBag.Book_ID = new SelectList(db.Books, "Id", "ISBN", listing.Book_ID);
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type", listing.Condition_Id);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value", listing.Status_ID);
            ViewBag.Course_ID = new SelectList(db.Courses, "Id", "Course_Name", listing.Course_ID);
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Email", listing.User_ID);
            return View(listing);
        }

        public ActionResult EditListing(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            ViewBag.Book_ID = new SelectList(db.Books, "Id", "ISBN", listing.Book_ID);
            ViewBag.Condition_Id = new SelectList(db.Conditions, "Id", "Type", listing.Condition_Id);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Value", listing.Status_ID);
            ViewBag.Course_ID = new SelectList(db.Courses, "Id", "Course_Name", listing.Course_ID);
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Email", listing.User_ID);
            return View(listing);
         
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateB([Bind(Include = "Id, ISBN,Title,Author_Name,Publisher_Name,Year,Edition,Image")]  Book book , HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                
                db.Books.Add(book);
                db.SaveChanges();
                Listing l = new Listing();
                l.Book_ID = book.Id;
                return IndexCreateBU(file, l, book);
                
            }

            return View(book);
        }
        public ActionResult Settings ()
        {
            return View(loggedInUser);
        }
        // GET: Books/Edit/5
        public ActionResult BookEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
           
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BookEdit([Bind(Include = "Id,ISBN,Title,Author_Name,Publisher_Name,Year,Edition,Image")] Book book)
        {
        
           
           
            if (ModelState.IsValid)
            {

Older Work/Boox - sophmore year website sample/BooX/BooX/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BooX.Controllers
{
    public class SettingsController : Controller
    {
        // GET: Settings
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult BookInfo()
        {
            return View();
        }
    }
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/Master/CreateB.cshtml
@model BooX.Models.Book

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_navbar.cshtml";
}

<style>
    .homepage {
        color: black;
        border: 10px solid #5e6bff;
        border-radius: 70px;
        font-size: 20px;
        width: auto;
        margin-left:auto;
        margin-right:auto;
    }

    input {
        border: 2px solid #5e6bff;
        border-radius: 15px;
        margin-left: 100px;
        width: auto;
        padding: 5px;
        align-items:center;
    }

    #sButton{
    width: 80%;
    float: right;
    background-color:#5e6bff;
    font-weight:bold;
    color: white;
    }
    td{
        text-align:left;
    }

</style>
<div id="title">
    <img src='@Url.Content("~/Content/Images/icon_plus.png")' style="width:150px; float:left;" />
    <h1 style="color:black"> Add Your Book </h1>
</div>
<div class="homepage">

    @using (Html.BeginForm("CreateB", "Master", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <table id="Book" cellpadding="10">
                <tr>
                    <td>Upload Image Here: </td>
                    <td><input type="file" name="file" id="file" value="Upload Book Cover" /></td>
                </tr>
                <tr>
                    <td>ISBN</td>
                    <td>
                        @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>Title</td>
                    <td>
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>Author</td>
                    <td>
                        @Html.EditorFor(model => model.Author_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Author_Name, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>Publisher</td>
                    <td>
                        @Html.EditorFor(model => model.Publisher_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Publisher_Name, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>Year</td>
                    <td>
                        @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>Edition</td>
                    <td>
                        @Html.EditorFor(model => model.Edition, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Edition, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Next" id="sButton" /></td>
                </tr>
            </table>
      </div>
     }
</div>       
     @*<div class="form-group">
            <label>Upload Image Here:</label>
                    <img src="~/Content/Images/book2.png" width="200" height="200">
                    <input type="file" name="file" id="file" value="Upload Book Cover" />
                
        </div>
       <div class="form-group">
                @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author_Name, "Author Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Author_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Publisher_Name, "Publisher Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Publisher_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Publisher_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Edition, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Edition, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Edition, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Next" class="btn btn-default" />
                </div>
            </div>
        </div>*@

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/Master/Listing1.cshtml
@model IEnumerable<BooX.Models.Listing>
<style>
   td{
       font-size:19pt;
   }
</style>

    @foreach (var item in Model)
    {<tr>
        <td>
            @{
        var imgName = item.Book_ID + ".jpg";
            }
            <img src="~/Content/BookImages/@imgName" alt="" height="150" width="112" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Book.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Book.ISBN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Book.Author_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Book.Publisher_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Book.Edition)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Book.Year)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Condition.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Course_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date_Listed)
        </td>
    </tr>
    }

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/Master/Login.cshtml
@model BooX.Models.User

@using (Html.BeginForm("Login", "Master", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
  

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="login" class="btn btn-default" />
            </div>
        </div>
        </div>
}

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/Master/MessageIndex.cshtml
@model IEnumerable<BooX.Models.Message>
@{Layout = "~/Views/Shared/_navbar.cshtml";}
<style type="text/css">   

    #nav a:hover {
        color: red;
    }
    .header {
        overflow: hidden;
        padding-left: 5px;
        margin-left:auto;
        margin-right:auto;
        width:auto;
    }
    td, th{
        font-size: 20px;
    }
    .homepage{
        border: 10px solid #ffae00;
        border-radius: 70px;
        width: 100%;
        color: black;
    }
</style>
<div class="homepage">
    <div class="header">
        <img src='@Url.Content("~/Content/Images/icon_envelope.png")' width="150" />
    </div>
    <div id="content">
        <table class="table" cellpadding="15">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Subject)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Content)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    Reply
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.ActionLink("Reply", "replyMessage", "Master", item, new { @class = "yourCSSclass", @style = "color: black;" })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Older Work/Boox - sophmore year website sample/BooX/BooX/Views/Master/Profile.cshtml
@using BooX.Models
 @model BooX.Models.User

    @{
        ViewBag.Title = "Profile";
        Layout = "~/Views/Shared/_navbar.cshtml";

    }
<style>
    input {
        border: 2px solid #bf00ff;
        border-radius: 15px;
        }
    body{
        zoom: .65001;
        align-content:center;
    }
    #profTable{
        font-size:20pt;
        width: inherit;
        /*border:2px dashed red;*/
        width: 1200px;
    }
    td{
        width:auto;
    }
    tr{
        /*border-bottom: 2px dotted black;*/
    }
    
.homepageProfile {
        zoom: .65;
        border: 10px solid #bf00ff;
        border-radius: 70px;
        background-color: white;
        font-size: 22pt;
        width: 1500px;
        overflow:auto;
        color: black;
        padding:0px;
        margin:0%;
        text-align:center;
        padding-top:1%;
        padding-left: 0px;
        padding-right: 0px;
        margin-left: auto;
        margin-right: auto;
    }
</style>

<div class="homepageProfile">
    @{
            var iName = "/Images/icon_smile-o.png";
            if (Model.ID != 0)
            {
                iName = "/UserImages/" + @Model.ID + ".jpg";
            }
            else if (Model.ID == 0)
            {
                iName = "/Images/icon_smile-o.png";
            }
    }
    <img src="~/Content/@iName" width="200" height="200" />
        <h1> @Model.Full_name </h1>
        <h2> @Model.Email</h2>
     <hr />
    <table id="profTable" cellpadding="10">
    <thead><tr>
        <th>Image</th>
        <th>Title</th>
        <th>ISBN</th>
        <th>Author</th>
        <th>Publisher</th>
        <th>Edition</th>
        <th>Year</th>
        <th>Price</th>
        <th>Condition</th>
        <th>Status</th>
        <th>Department</th>
        <th>Date Listed</th>
    </tr></thead>
     @Html.Action("Listing1", "Master", new { user = Model })
      </table>  
</div>